import fs from 'fs'
import path from 'path'
import type { ResolvedConfig } from '../config/types'
import { generateWalletModulesCode } from './wallet-modules'
import { generateProtocolModulesCode } from './protocol-modules'
import { DEFAULT_ENTRY_FILENAME } from '../constants'

export async function generateJsonRpcEntryPoint (config: ResolvedConfig, outputDir: string): Promise<string> {
  const walletModulesCode = generateWalletModulesCode(config)
  const protocolModulesCode = generateProtocolModulesCode(config)

  const entryCode = `
// Auto-generated by @tetherto/wdk-worklet-bundler
// Generated at: ${new Date().toISOString()}
// Transport: jsonrpc
// DO NOT EDIT MANUALLY

require('bare-node-runtime/global')

// .mjs patch: JSC on iOS/darwin has no js_create_module, force .mjs to load as CJS
if (Bare.platform === 'ios' || Bare.platform === 'darwin') {
  module.constructor._extensions['.mjs'] = module.constructor._extensions['.js']
}

const { globalAgent } = require('bare-http1')

if (typeof Bare !== 'undefined' && Bare.on) {
  Bare.on('unhandledRejection', (error) => {
    console.error('Unhandled promise rejection in worklet:', error)
  })
  Bare.on('uncaughtException', (error) => {
    console.error('Uncaught exception in worklet:', error)
  })
  Bare.on('suspend', () => {
    globalAgent.suspend()
    console.log('Fetching in worklet suspended', globalAgent.suspended)
  })
  Bare.on('resume', () => {
    globalAgent.resume()
    console.log('Fetching in worklet resumed', globalAgent.resumed)
  })
  Bare.on('exit', () => {
    if (context.wdk) {
      try { context.wdk.dispose() } catch (e) {}
      context.wdk = null
    }
  })
}

const { IPC: BareIPC } = BareKit
const { registerJsonRpcHandlers, utils } = require('@tetherto/pear-wrk-wdk/jsonrpc', { with: { imports: 'bare-node-runtime/imports' } })
const { logger } = utils

// ============================================================
// WALLET MODULES (Generated from config)
// ============================================================
${walletModulesCode}

// ============================================================
// PROTOCOL MODULES (Generated from config)
// ============================================================
${protocolModulesCode}

let wdk = null

const context = {
  WDK,
  walletManagers,
  protocolManagers: typeof protocolManagers !== 'undefined' ? protocolManagers : {},
  wdkLoadError: null,
  get wdk () { return wdk },
  set wdk (value) { wdk = value }
}

registerJsonRpcHandlers(BareIPC, context)
logger.info('Worklet started (jsonrpc)')
`.trim()

  await fs.promises.mkdir(outputDir, { recursive: true })

  const entryPath = path.join(outputDir, DEFAULT_ENTRY_FILENAME)
  await fs.promises.writeFile(entryPath, entryCode, 'utf-8')

  return entryPath
}
