import fs from 'fs'
import path from 'path'
import type { ResolvedConfig } from '../config/types'
import { generateWalletModulesCode } from './wallet-modules'
import { generateProtocolModulesCode } from './protocol-modules'
import { DEFAULT_ENTRY_FILENAME } from '../constants'

export async function generateJsonRpcEntryPoint (config: ResolvedConfig, outputDir: string): Promise<string> {
  const walletModulesCode = generateWalletModulesCode(config)
  const protocolModulesCode = generateProtocolModulesCode(config)

  const entryCode = `
// Auto-generated by @tetherto/wdk-worklet-bundler
// Generated at: ${new Date().toISOString()}
// Transport: jsonrpc
// DO NOT EDIT MANUALLY

// Polyfills for JSC (TextEncoder, process, etc.) - must be first
require('bare-node-runtime/global')

// Force .mjs files to load as CJS (JSC has no js_create_module)
if (Bare.platform === 'ios' || Bare.platform === 'darwin') {
  module.constructor._extensions['.mjs'] = module.constructor._extensions['.js']
}

const {
  registerJsonRpcHandlers,
  utils: { logger }
} = require('@tetherto/pear-wrk-wdk/jsonrpc')

// Catch termination signal from BareKit (when Swift calls worklet.terminate())
// Without this, Bare's default handler calls C abort(), killing the host app.
Bare.on('uncaughtException', (err) => {
  logger.error('Caught exception in worklet:', err)
})

Bare.on('exit', () => {
  if (context.wdk) {
    try { context.wdk.dispose() } catch (e) {}
    context.wdk = null
  }
})

if (typeof process !== 'undefined' && process.on) {
  process.on('unhandledRejection', (error) => {
    logger.error('Unhandled promise rejection in worklet:', error)
  })
  process.on('uncaughtException', (error) => {
    logger.error('Uncaught exception in worklet:', error)
  })
}

// ============================================================
// WALLET MODULES (Generated from config)
// ============================================================
${walletModulesCode}

// ============================================================
// PROTOCOL MODULES (Generated from config)
// ============================================================
${protocolModulesCode}

// === Context (passed to all handlers) ===

let wdk = null

const context = {
  WDK,
  walletManagers,
  protocolManagers: typeof protocolManagers !== 'undefined' ? protocolManagers : {},
  wdkLoadError,
  get wdk () { return wdk },
  set wdk (value) { wdk = value }
}

// === Initialize BareKit IPC and register handlers ===

// eslint-disable-next-line no-undef
const { IPC: BareIPC } = BareKit
logger.info('BareKit IPC initialized')

registerJsonRpcHandlers(BareIPC, context)
logger.info('WDK Worklet ready - listening for JSON-RPC messages')
`.trim()

  await fs.promises.mkdir(outputDir, { recursive: true })

  const entryPath = path.join(outputDir, DEFAULT_ENTRY_FILENAME)
  await fs.promises.writeFile(entryPath, entryCode, 'utf-8')

  return entryPath
}
