import fs from 'fs'
import path from 'path'
import type { ResolvedConfig } from '../config/types'
import { generateWalletModulesCode } from './wallet-modules'
import { generateProtocolModulesCode } from './protocol-modules'
import { DEFAULT_ENTRY_FILENAME } from '../constants'

export async function generateEntryPoint(config: ResolvedConfig, outputDir: string): Promise<string> {
  const walletModulesCode = generateWalletModulesCode(config)
  const protocolModulesCode = generateProtocolModulesCode(config)

  const entryCode = `
// Auto-generated by @tetherto/wdk-worklet-bundler
// Generated at: ${new Date().toISOString()}
// DO NOT EDIT MANUALLY

// Handle unhandled promise rejections and exceptions
if (typeof Bare !== 'undefined' && Bare.on) {
  Bare.on('unhandledRejection', (error) => {
    console.error('Unhandled promise rejection in worklet:', error);
  })
  Bare.on('uncaughtException', (error) => {
    console.error('Uncaught exception in worklet:', error);
  })
}

require('bare-node-runtime/global');

const { IPC: BareIPC } = BareKit
const { HRPC, registerRpcHandlers, utils } = require('@tetherto/pear-wrk-wdk/worklet', { with: { imports: 'bare-node-runtime/imports' }});
const { logger } = utils;

// ============================================================
// WALLET MODULES (Generated from config)
// ============================================================
${walletModulesCode}

// ============================================================
// PROTOCOL MODULES (Generated from config)
// ============================================================
${protocolModulesCode}

const rpc = new HRPC(BareIPC);

let wdk = null;

const context = {
  wdk,
  WDK,
  walletManagers,
  protocolManagers: typeof protocolManagers !== 'undefined' ? protocolManagers : {},
  wdkLoadError: null
}

registerRpcHandlers(rpc, context);
logger.info('Worklet started');
`.trim()

  // Ensure output directory exists
  await fs.promises.mkdir(outputDir, { recursive: true })

  const entryPath = path.join(outputDir, DEFAULT_ENTRY_FILENAME)
  await fs.promises.writeFile(entryPath, entryCode, 'utf-8')

  return entryPath
}
