import fs from 'fs'
import path from 'path'
import type { ResolvedConfig } from '../config/types'
import { generateWalletModulesCode } from './wallet-modules'
import { generateProtocolModulesCode } from './protocol-modules'
import { generateModuleModulesCode } from './module-modules'
import { DEFAULT_ENTRY_FILENAME } from '../constants'

export async function generateEntryPoint (config: ResolvedConfig, outputDir: string): Promise<string> {
  const walletModulesCode = generateWalletModulesCode(config)
  const protocolModulesCode = generateProtocolModulesCode(config)
  const moduleModulesCode = generateModuleModulesCode(config)

  const entryCode = `
// Auto-generated by @tetherto/wdk-worklet-bundler
// Generated at: ${new Date().toISOString()}
// DO NOT EDIT MANUALLY

require('bare-node-runtime/global');
const { globalAgent: http1Agent } = require('bare-http1')
const { globalAgent: httpsAgent } = require('bare-https')

const agents = [http1Agent, httpsAgent]

// Handle unhandled promise rejections and exceptions
if (typeof Bare !== 'undefined' && Bare.on) {
  Bare.on('unhandledRejection', (error) => {
    console.error('Unhandled promise rejection in worklet:', error);
  })
  Bare.on('uncaughtException', (error) => {
    console.error('Uncaught exception in worklet:', error);
  })
  Bare.on('suspend', () => {
    agents.forEach((globalAgent) => {
      globalAgent.suspend()
      console.log('Fetching in worklet suspended', globalAgent.suspended)
    })
  })
  Bare.on('resume', () => {
    agents.forEach((globalAgent) => {
      globalAgent.resume()
      console.log('Fetching in worklet resumed', globalAgent.resumed)
    })
  })
}


const { IPC: BareIPC } = BareKit
const { HRPC, registerRpcHandlers, utils } = require('@tetherto/pear-wrk-wdk/worklet', { with: { imports: 'bare-node-runtime/imports' }});
const { logger } = utils;

// ============================================================
// WALLET MODULES (Generated from config)
// ============================================================
${walletModulesCode}

// ============================================================
// PROTOCOL MODULES (Generated from config)
// ============================================================
${protocolModulesCode}

// ============================================================
// MODULES (Generated from config)
// ============================================================
${moduleModulesCode}

const rpc = new HRPC(BareIPC);

let wdk = null;

const context = {
  wdk,
  WDK,
  walletManagers,
  protocolManagers: typeof protocolManagers !== 'undefined' ? protocolManagers : {},
  moduleManagers: typeof moduleManagers !== 'undefined' ? moduleManagers : {},
  allowedMethods: ${JSON.stringify(config.allowedMethods ?? {})},
  wdkLoadError: null
}

registerRpcHandlers(rpc, context);

// Drive module suspend/resume from the worklet's Bare lifecycle (the same signal
// the HTTP agents use), so modules release sockets/storage when the app backgrounds.
if (typeof Bare !== 'undefined' && Bare.on && context.moduleRuntime) {
  Bare.on('suspend', () => {
    context.moduleRuntime.suspendAll()
  })
  Bare.on('resume', () => {
    context.moduleRuntime.resumeAll()
  })
}

logger.info('Worklet started');
`.trim()

  // Ensure output directory exists
  await fs.promises.mkdir(outputDir, { recursive: true })

  const entryPath = path.join(outputDir, DEFAULT_ENTRY_FILENAME)
  await fs.promises.writeFile(entryPath, entryCode, 'utf-8')

  return entryPath
}
