/**
 * Bundle generator
 * Orchestrates the full bundle generation process
 */

import fs from 'fs'
import path from 'path'
import { execFileSync } from 'child_process'
import type { ResolvedConfig } from '../config/types'
import { generateEntryPoint } from '../generators/entry'
import { generateJsonRpcEntryPoint } from '../generators/entry-jsonrpc'
import { linkAddons } from './addons'
import { convertBundleEsmToCjs } from './convert-esm-to-cjs'
import { validateDependencies, findMissingOptionalPeers } from '../validators/dependencies'
import { getPackageList } from '../config/packages'
import { DEFAULT_BUNDLE_BUILD_HOSTS, DEFAULT_OUTPUT_DIR, DEFAULT_ENTRY_FILENAME } from '../constants'

export type { LinkAddonsOptions, LinkAddonsResult } from './addons'
export { linkAddons } from './addons'

export interface GenerateBundleOptions {
  dryRun?: boolean
  verbose?: boolean
  silent?: boolean
  skipTypes?: boolean
  skipGeneration?: boolean
  /** Defer missing optional peer deps to runtime instead of failing (default: true) */
  deferOptionalPeers?: boolean
}

export interface GenerateBundleResult {
  success: boolean
  bundlePath: string
  typesPath: string
  bundleSize: number
  duration: number
  error?: string
  missingModule?: string
}

interface BarePackOptions {
  entryPath: string
  outputPath: string
  importsPath: string
  targets: string[]
  cwd: string
  verbose?: boolean
  /** Module specifiers whose resolution is deferred to runtime (missing optional peers) */
  defer?: string[]
}

class MissingModuleError extends Error {
  constructor (public readonly missingModule: string) {
    super(`Missing module: ${missingModule}`)
    this.name = 'MissingModuleError'
  }
}

/**
 * Run bare-pack to create the final bundle
 */
function runBarePack (options: BarePackOptions): void {
  const { entryPath, outputPath, importsPath, targets, cwd, verbose, defer } = options

  // Build args array to prevent command injection
  const args = ['--no-install', 'bare-pack']
  for (const target of targets) {
    // Validate target format (alphanumeric with dashes only)
    if (!/^[a-z0-9-]+$/i.test(target)) {
      throw new Error(`Invalid target format: ${target}`)
    }
    args.push('--host', target)
  }
  for (const specifier of defer ?? []) {
    // Validate npm package name format (optionally scoped)
    if (!/^(@[a-z0-9-~][a-z0-9-._~]*\/)?[a-z0-9-~][a-z0-9-._~]*$/i.test(specifier)) {
      throw new Error(`Invalid defer specifier format: ${specifier}`)
    }
    args.push('--defer', specifier)
  }
  args.push('--linked', '--imports', importsPath, '--out', outputPath, entryPath)

  if (verbose === true) {
    console.log(`  Running: npx ${args.join(' ')}`)
    console.log(`  CWD: ${cwd}`)
  }

  try {
    execFileSync('npx', args, {
      cwd,
      stdio: verbose === true ? 'inherit' : 'pipe'
    })
  } catch (error) {
    // Try to extract stdout/stderr if available
    const execError = error as { stderr?: Buffer | string, stdout?: Buffer | string }
    const stderr: string = execError.stderr != null ? execError.stderr.toString() : ''
    const stdout: string = execError.stdout != null ? execError.stdout.toString() : ''
    const output = stderr + stdout

    // Check for missing module error
    const match = output.match(/MODULE_NOT_FOUND: Cannot find module '(.+?)'/)
    if (match?.[1]) {
      throw new MissingModuleError(match[1])
    }

    // Re-throw original error if we couldn't parse it
    throw error
  }
}

/**
 * Generate the pack.imports.json file
 */
function generateImportsFile (outputDir: string): string {
  const imports = {}

  const importsPath = path.join(outputDir, 'pack.imports.json')
  fs.writeFileSync(importsPath, JSON.stringify(imports, null, 2))

  return importsPath
}

/**
 * Generate the index.js file that exports bundle and HRPC
 * This allows importing from './.wdk' directly
 */
function generateIndexFile (outputDir: string, bundlePath: string): void {
  const indexPath = path.join(outputDir, 'index.js')

  // path.relative returns 'a/b' or '../a/b'. Node's CommonJS resolver
  // requires the './' prefix on same-dir / nested paths.
  let relativeBundle = path.relative(outputDir, bundlePath)
  if (!relativeBundle.startsWith('.')) {
    relativeBundle = './' + relativeBundle
  }

  // On Windows, path.relative returns backslashes; require() needs forward.
  relativeBundle = relativeBundle.split(path.sep).join('/')

  const indexContent = `/**
 * WDK Bundle Exports
 * Generated by @tetherto/wdk-worklet-bundler
 */

const bundle = require('${relativeBundle}')

module.exports = {
  bundle
}
`
  fs.writeFileSync(indexPath, indexContent)
}

/**
 * Get default targets based on platform
 */
function getDefaultHosts (): string[] {
  return DEFAULT_BUNDLE_BUILD_HOSTS
}

/**
 * Generate WDK bundle from configuration
 */
export async function generateBundle (
  config: ResolvedConfig,
  options: GenerateBundleOptions = {}
): Promise<GenerateBundleResult> {
  const startTime = Date.now()
  const { dryRun, verbose, silent } = options

  const log = (msg: string): void => {
    if (!silent) console.log(msg)
  }

  const generatedDir = path.join(config.projectRoot, DEFAULT_OUTPUT_DIR)

  const isJsonRpc = config.transport === 'jsonrpc'
  const shouldLinkAddons = config.options?.linkAddons ?? isJsonRpc

  if (dryRun) {
    log(`Dry run - would generate (transport: ${config.transport ?? 'hrpc'}):`)
    log(`  Output dir: ${generatedDir}`)
    log(`  Entry: ${generatedDir}/wdk-worklet.generated.js`)
    log(`  Bundle: ${config.resolvedOutput.bundle}`)
    if (!options.skipTypes) {
      log(`  Types: ${config.resolvedOutput.types}`)
    }
    if (shouldLinkAddons) {
      const platforms = config.options?.platforms ?? ['ios', 'macos', 'android']
      for (const p of platforms) {
        log(`  Addons (${p}): ${config.resolvedOutput.addons[p]}`)
      }
    }

    return {
      success: true,
      bundlePath: config.resolvedOutput.bundle,
      typesPath: config.resolvedOutput.types,
      bundleSize: 0,
      duration: Date.now() - startTime
    }
  }

  try {
    // Ensure output directories exist
    fs.mkdirSync(generatedDir, { recursive: true })
    fs.mkdirSync(path.dirname(config.resolvedOutput.bundle), { recursive: true })

    // Step 1-3: Generate artifacts or use existing
    let entryPath: string
    let importsPath: string

    if (options.skipGeneration) {
      if (verbose) log('  Skipping artifact generation, using existing files...')

      entryPath = path.join(generatedDir, DEFAULT_ENTRY_FILENAME)
      importsPath = path.join(generatedDir, 'pack.imports.json')

      if (!fs.existsSync(entryPath)) {
        throw new Error(`Artifacts not found at ${entryPath}. Run without --skip-generation first.`)
      }
      if (!fs.existsSync(importsPath)) {
        throw new Error(`Artifacts not found at ${importsPath}. Run without --skip-generation first.`)
      }
    } else {
      // Step 1: Generate worklet entry point (dispatch by transport)
      if (verbose) log(`  Generating ${isJsonRpc ? 'JSON-RPC' : 'HRPC'} worklet entry point...`)
      entryPath = isJsonRpc
        ? await generateJsonRpcEntryPoint(config, generatedDir)
        : await generateEntryPoint(config, generatedDir)
      if (verbose) log(`    Entry: ${entryPath}`)

      // Step 2: Generate imports file
      if (verbose) log('  Generating imports file...')
      importsPath = generateImportsFile(generatedDir)
    }

    // Step 4: Run bare-pack
    if (verbose) log('  Running bare-pack...')
    const targets = config.options?.targets || getDefaultHosts()

    // Missing peers marked optional via peerDependenciesMeta (e.g.
    // @ledgerhq/ledger-bitcoin for @bitcoinerlab/descriptors) are deferred so
    // bare-pack doesn't fail statically resolving imports the app never uses.
    // --no-defer-optional-peers disables this for apps that use those
    // features and want to find out at build time instead of runtime.
    let deferredPeers: string[] = []
    if (options.deferOptionalPeers !== false) {
      const { installed } = validateDependencies(getPackageList(config), config.projectRoot)
      deferredPeers = findMissingOptionalPeers(installed, config.projectRoot, { verbose })
      if (deferredPeers.length > 0) {
        log(`  Deferring missing optional peer dependencies: ${deferredPeers.join(', ')}`)
      }
    }

    try {
      runBarePack({
        entryPath,
        outputPath: config.resolvedOutput.bundle,
        importsPath,
        targets,
        cwd: config.projectRoot,
        verbose,
        defer: deferredPeers
      })
    } catch (barePackError) {
      // Check if we identified a missing module
      if (barePackError instanceof MissingModuleError) {
        return {
          success: false,
          bundlePath: config.resolvedOutput.bundle,
          typesPath: config.resolvedOutput.types,
          bundleSize: 0,
          duration: Date.now() - startTime,
          error: `Missing module: ${barePackError.missingModule}`,
          missingModule: barePackError.missingModule
        }
      }

      // bare-pack failed - provide helpful error message
      const errorMsg = barePackError instanceof Error ? barePackError.message : String(barePackError)

      return {
        success: false,
        bundlePath: config.resolvedOutput.bundle,
        typesPath: config.resolvedOutput.types,
        bundleSize: 0,
        duration: Date.now() - startTime,
        error:
          `bare-pack failed: ${errorMsg}\n\n` +
          'This usually means:\n' +
          '  1. WDK modules are not installed in the project\n' +
          '  2. A dependency uses Node.js APIs not available in Bare runtime\n\n' +
          'Generated files are available at:\n' +
          `  Entry: ${entryPath}\n` +
          'You can run bare-pack manually once dependencies are resolved.'
      }
    }

    // Step 4b: Convert ESM to CJS in bundle (needed for JSC runtimes like iOS/macOS)
    const shouldConvertCjs = config.options?.convertEsmToCjs ?? isJsonRpc
    if (shouldConvertCjs) {
      if (verbose) log('  Converting ESM to CJS in bundle...')
      convertBundleEsmToCjs(config.resolvedOutput.bundle, { minify: true, verbose })
    }

    // Get bundle stats
    let bundleSize = 0
    if (fs.existsSync(config.resolvedOutput.bundle)) {
      bundleSize = fs.statSync(config.resolvedOutput.bundle).size
    }

    // Step 5: Link native addons (if enabled, or always for jsonrpc unless explicitly disabled)
    if (shouldLinkAddons) {
      if (verbose) log('  Linking native addons...')
      const addonsResult = await linkAddons(config, { verbose, silent })
      if (!addonsResult.success) {
        log(`  Warning: bare-link failed: ${addonsResult.error}`)
      }
    }

    // Step 7: Generate TypeScript declarations (optional)
    if (!options.skipTypes) {
      if (verbose) log('  Generating TypeScript declarations...')
      generateTypeDeclarations(config)
    }

    // Step 8: Generate index.js for easy importing
    if (verbose) log('  Generating index.js...')
    generateIndexFile(generatedDir, config.resolvedOutput.bundle)

    return {
      success: true,
      bundlePath: config.resolvedOutput.bundle,
      typesPath: config.resolvedOutput.types,
      bundleSize,
      duration: Date.now() - startTime
    }
  } catch (error) {
    return {
      success: false,
      bundlePath: config.resolvedOutput.bundle,
      typesPath: config.resolvedOutput.types,
      bundleSize: 0,
      duration: Date.now() - startTime,
      error: error instanceof Error ? error.message : String(error)
    }
  }
}

/**
 * Generate TypeScript declarations for the bundle
 */
function generateTypeDeclarations (config: ResolvedConfig): void {
  // Generate index.d.ts in .wdk folder for proper module resolution
  const generatedDir = path.join(config.projectRoot, '.wdk')
  const indexDtsPath = path.join(generatedDir, 'index.d.ts')
  fs.mkdirSync(generatedDir, { recursive: true })

  const networks = Object.keys(config.networks)
  const protocols = (config.protocols != null) ? Object.keys(config.protocols) : []

  const declarations = `
/**
 * WDK Bundle TypeScript Declarations
 * Generated by @tetherto/wdk-worklet-bundler
 * Generated at: ${new Date().toISOString()}
 */

export type NetworkName = ${networks.map((n) => `'${n}'`).join(' | ')};
export type ProtocolName = ${(protocols.length > 0) ? protocols.map((n) => `'${n}'`).join(' | ') : 'never'};

export const bundle: string;
`

  fs.writeFileSync(indexDtsPath, declarations)
}

/**
 * Generate only the entry point
 * Useful for debugging or custom bundling workflows
 */
export async function generateSourceFiles (
  config: ResolvedConfig,
  options: { verbose?: boolean } = {}
): Promise<{ entryPath: string }> {
  const generatedDir = path.join(config.projectRoot, DEFAULT_OUTPUT_DIR)

  // Generate worklet entry point (dispatch by transport)
  const isJsonRpc = config.transport === 'jsonrpc'
  if (options.verbose) console.log(`  Generating ${isJsonRpc ? 'JSON-RPC' : 'HRPC'} worklet entry point...`)
  const entryPath = isJsonRpc
    ? await generateJsonRpcEntryPoint(config, generatedDir)
    : await generateEntryPoint(config, generatedDir)

  // Generate imports file
  generateImportsFile(generatedDir)

  // Generate index.js for easy importing (note: bundle won't exist yet in source-only mode)
  // Users will need to run bare-pack first, but we create the index anyway
  generateIndexFile(generatedDir, config.resolvedOutput.bundle)

  return {
    entryPath
  }
}
