/**
 * Bundle generator
 * Orchestrates the full bundle generation process
 */

import fs from 'fs'
import path from 'path'
import { execSync } from 'child_process'
import type { ResolvedConfig } from '../config/types'
import { generateEntryPoint } from '../generators/entry'
import { generateHrpc } from '../generators/hrpc'

export interface GenerateBundleOptions {
  dryRun?: boolean
  verbose?: boolean
  silent?: boolean
  skipTypes?: boolean
}

export interface GenerateBundleResult {
  success: boolean
  bundlePath: string
  typesPath: string
  bundleSize: number
  duration: number
  error?: string
}

interface BarePackOptions {
  entryPath: string
  outputPath: string
  importsPath: string
  targets: string[]
  cwd: string
  verbose?: boolean
}

/**
 * Run bare-pack to create the final bundle
 */
function runBarePack(options: BarePackOptions): void {
  const { entryPath, outputPath, importsPath, targets, cwd, verbose } = options

  // Build args array to prevent command injection
  const args = ['bare-pack']
  for (const target of targets) {
    // Validate target format (alphanumeric with dashes only)
    if (!/^[a-z0-9-]+$/i.test(target)) {
      throw new Error(`Invalid target format: ${target}`)
    }
    args.push('--target', target)
  }
  args.push('--linked', '--imports', importsPath, '--out', outputPath, entryPath)

  if (verbose) {
    console.log(`  Running: npx ${args.join(' ')}`)
    console.log(`  CWD: ${cwd}`)
  }

  execSync(`npx ${args.join(' ')}`, {
    cwd,
    stdio: verbose ? 'inherit' : 'pipe',
  })
}

/**
 * Generate the pack.imports.json file
 */
function generateImportsFile(outputDir: string): string {
  const imports = {
    BareKit: 'bare:kit',
    // Map node:crypto to bare-crypto for Bare runtime compatibility
    'node:crypto': 'bare-crypto',
  }

  const importsPath = path.join(outputDir, 'pack.imports.json')
  fs.writeFileSync(importsPath, JSON.stringify(imports, null, 2))

  return importsPath
}

/**
 * Generate the index.js file that exports bundle and HRPC
 * This allows importing from './.wdk' directly
 */
function generateIndexFile(outputDir: string): void {
  const indexContent = `/**
 * WDK Bundle Exports
 * Generated by @tetherto/wdk-worklet-bundler
 */

const bundle = require('./wdk.bundle.js');
const HRPC = require('./hrpc/index.js');

module.exports = {
  bundle,
  HRPC
};
`

  const indexPath = path.join(outputDir, 'index.js')
  fs.writeFileSync(indexPath, indexContent)
}

/**
 * Get default targets based on platform
 */
function getDefaultTargets(): string[] {
  return ['ios-arm64', 'ios-arm64-simulator', 'android-arm64', 'android-arm']
}

/**
 * Generate WDK bundle from configuration
 */
export async function generateBundle(
  config: ResolvedConfig,
  options: GenerateBundleOptions = {}
): Promise<GenerateBundleResult> {
  const startTime = Date.now()
  const { dryRun, verbose, silent } = options

  const log = (msg: string) => {
    if (!silent) console.log(msg)
  }

  const generatedDir = path.join(config.projectRoot, '.wdk')

  if (dryRun) {
    log('Dry run - would generate:')
    log(`  Output dir: ${generatedDir}`)
    log(`  Entry: ${generatedDir}/wdk-worklet.generated.js`)
    log(`  HRPC: ${generatedDir}/hrpc/`)
    log(`  Schema: ${generatedDir}/schema/`)
    log(`  Bundle: ${config.resolvedOutput.bundle}`)
    if (!options.skipTypes) {
      log(`  Types: ${config.resolvedOutput.types}`)
    }

    return {
      success: true,
      bundlePath: config.resolvedOutput.bundle,
      typesPath: config.resolvedOutput.types,
      bundleSize: 0,
      duration: Date.now() - startTime,
    }
  }

  try {
    // Ensure output directories exist
    fs.mkdirSync(generatedDir, { recursive: true })
    fs.mkdirSync(path.dirname(config.resolvedOutput.bundle), { recursive: true })

    // Step 1: Generate HRPC bindings
    if (verbose) log('  Generating HRPC bindings...')
    const hrpcResult = await generateHrpc(generatedDir)
    if (verbose) {
      log(`    Schema: ${hrpcResult.schemaDir}`)
      log(`    HRPC: ${hrpcResult.hrpcDir}`)
    }

    // Step 2: Generate worklet entry point
    if (verbose) log('  Generating worklet entry point...')
    const entryPath = await generateEntryPoint(config, generatedDir)
    if (verbose) log(`    Entry: ${entryPath}`)

    // Step 3: Generate imports file
    if (verbose) log('  Generating imports file...')
    const importsPath = generateImportsFile(generatedDir)

    // Step 4: Run bare-pack
    if (verbose) log('  Running bare-pack...')
    const targets = config.options?.targets || getDefaultTargets()

    try {
      runBarePack({
        entryPath,
        outputPath: config.resolvedOutput.bundle,
        importsPath,
        targets,
        cwd: config.projectRoot,
        verbose,
      })
    } catch (barePackError) {
      // bare-pack failed - provide helpful error message
      const errorMsg = barePackError instanceof Error ? barePackError.message : String(barePackError)

      return {
        success: false,
        bundlePath: config.resolvedOutput.bundle,
        typesPath: config.resolvedOutput.types,
        bundleSize: 0,
        duration: Date.now() - startTime,
        error:
          `bare-pack failed: ${errorMsg}\n\n` +
          'This usually means:\n' +
          '  1. WDK modules are not installed in the project\n' +
          '  2. A dependency uses Node.js APIs not available in Bare runtime\n\n' +
          'Generated files are available at:\n' +
          `  Entry: ${entryPath}\n` +
          `  HRPC: ${hrpcResult.hrpcDir}\n\n` +
          'You can run bare-pack manually once dependencies are resolved.',
      }
    }

    // Get bundle stats
    let bundleSize = 0
    if (fs.existsSync(config.resolvedOutput.bundle)) {
      bundleSize = fs.statSync(config.resolvedOutput.bundle).size
    }

    // Step 5: Generate TypeScript declarations (optional)
    if (!options.skipTypes) {
      if (verbose) log('  Generating TypeScript declarations...')
      await generateTypeDeclarations(config)
    }

    // Step 6: Generate index.js for easy importing
    if (verbose) log('  Generating index.js...')
    generateIndexFile(generatedDir)

    return {
      success: true,
      bundlePath: config.resolvedOutput.bundle,
      typesPath: config.resolvedOutput.types,
      bundleSize,
      duration: Date.now() - startTime,
    }
  } catch (error) {
    return {
      success: false,
      bundlePath: config.resolvedOutput.bundle,
      typesPath: config.resolvedOutput.types,
      bundleSize: 0,
      duration: Date.now() - startTime,
      error: error instanceof Error ? error.message : String(error),
    }
  }
}

/**
 * Generate TypeScript declarations for the bundle
 */
async function generateTypeDeclarations(config: ResolvedConfig): Promise<void> {
  // Generate index.d.ts in .wdk folder for proper module resolution
  const generatedDir = path.join(config.projectRoot, '.wdk')
  const indexDtsPath = path.join(generatedDir, 'index.d.ts')
  fs.mkdirSync(generatedDir, { recursive: true })

  const networks = Object.keys(config.networks)

  const declarations = `/**
 * WDK Bundle TypeScript Declarations
 * Generated by @tetherto/wdk-worklet-bundler
 * Generated at: ${new Date().toISOString()}
 */

export type NetworkName = ${networks.map((n) => `'${n}'`).join(' | ')};

export interface WdkInitializeParams {
  encryptionKey: string;
  encryptedSeed: string;
  config?: string;
}

export interface WdkGenerateEntropyParams {
  wordCount: 12 | 24;
}

export interface WdkEntropyResult {
  encryptionKey: string;
  encryptedSeedBuffer: string;
  encryptedEntropyBuffer: string;
}

export interface WdkGetMnemonicParams {
  encryptedEntropy: string;
  encryptionKey: string;
}

export interface WdkCallMethodParams {
  methodName: string;
  network: NetworkName;
  accountIndex: number;
  args?: string;
}

export interface WdkWorklet {
  workletStart(params: { config: string }): Promise<{ status: string }>;
  initializeWDK(params: WdkInitializeParams): Promise<{ status: string }>;
  generateEntropyAndEncrypt(params: WdkGenerateEntropyParams): Promise<WdkEntropyResult>;
  getMnemonicFromEntropy(params: WdkGetMnemonicParams): Promise<{ mnemonic: string }>;
  getSeedAndEntropyFromMnemonic(params: { mnemonic: string }): Promise<WdkEntropyResult>;
  callMethod(params: WdkCallMethodParams): Promise<{ result: string }>;
  dispose(): void;
}

export interface NetworkConfig {
  chainId: number;
  blockchain: string;
  provider?: string;
  [key: string]: unknown;
}

export type NetworkConfigs = {
  [K in NetworkName]: NetworkConfig;
};

/**
 * Embedded network configurations
 */
export const embeddedNetworks: NetworkName[] = ${JSON.stringify(networks)};

/**
 * The worklet bundle (for react-native-bare-kit)
 */
export const bundle: unknown;

/**
 * HRPC class for RPC communication with the worklet
 */
export const HRPC: new (ipc: unknown) => WdkWorklet;
`

  fs.writeFileSync(indexDtsPath, declarations)
}

/**
 * Generate only the entry point and HRPC (no bare-pack)
 * Useful for debugging or custom bundling workflows
 */
export async function generateSourceFiles(
  config: ResolvedConfig,
  options: { verbose?: boolean } = {}
): Promise<{ entryPath: string; hrpcDir: string; schemaDir: string }> {
  const generatedDir = path.join(config.projectRoot, '.wdk')

  // Generate HRPC bindings
  if (options.verbose) console.log('  Generating HRPC bindings...')
  const hrpcResult = await generateHrpc(generatedDir)

  // Generate worklet entry point
  if (options.verbose) console.log('  Generating worklet entry point...')
  const entryPath = await generateEntryPoint(config, generatedDir)

  // Generate imports file
  generateImportsFile(generatedDir)

  // Generate index.js for easy importing (note: bundle won't exist yet in source-only mode)
  // Users will need to run bare-pack first, but we create the index anyway
  generateIndexFile(generatedDir)

  return {
    entryPath,
    hrpcDir: hrpcResult.hrpcDir,
    schemaDir: hrpcResult.schemaDir,
  }
}
