/**
 * Bundle generator
 * Orchestrates the full bundle generation process
 */

import fs from 'fs'
import path from 'path'
import type { ResolvedConfig } from '../config/types'
import { shouldConvertEsmToCjs } from '../config/loader'
import { generateEntryPoint } from '../generators/entry'
import { generateJsonRpcEntryPoint } from '../generators/entry-jsonrpc'
import { linkAddons } from './addons'
import { linkPlatformsForHosts } from './linked-addons'
import { MissingModuleError, packBundle, type EsmToCjsStats } from './pack'
import { writeBundleFile } from './bundle-file'
import { validateDependencies, findMissingOptionalPeers } from '../validators/dependencies'
import { getPackageList } from '../config/packages'
import { DEFAULT_BUNDLE_BUILD_HOSTS, DEFAULT_OUTPUT_DIR, DEFAULT_ENTRY_FILENAME } from '../constants'

export type { LinkAddonsOptions, LinkAddonsResult } from './addons'
export { linkAddons } from './addons'
export type { PackBundleOptions, PackBundleResult, EsmToCjsStats, ConditionalSpecifier } from './pack'
export { packBundle, MissingModuleError } from './pack'

export interface GenerateBundleOptions {
  dryRun?: boolean
  verbose?: boolean
  silent?: boolean
  skipTypes?: boolean
  skipGeneration?: boolean
  deferOptionalPeers?: boolean
}

/** What bare-pack produced, as recorded in the bundle header. */
export interface GenerateBundlePackInfo {
  /** Hex content hash stamped into the header. */
  id: string
  /** Hosts the bundle was packed for. */
  hosts: string[]
  /** Number of files in the bundle. */
  files: number
  /** Addon hrefs in the header (`linked:` URLs the app must ship, `builtin:` ones the host embeds). */
  addons: string[]
  /** Whether the bundle still carries ES modules (see PackBundleResult.containsEsm). */
  containsEsm: boolean
  /** ESM→CJS conversion counters, or null when conversion was off. */
  esmToCjs: EsmToCjsStats | null
}

export interface GenerateBundleResult {
  success: boolean
  bundlePath: string
  typesPath: string
  /** Size of the bundle file written, wrapper included. */
  bundleSize: number
  duration: number
  /** Present once packing succeeded (also on a failure in a later step). */
  pack?: GenerateBundlePackInfo
  error?: string
  missingModule?: string
}

/**
 * Generate the index.js file that exports bundle and HRPC
 * This allows importing from './.wdk' directly
 */
function generateIndexFile (outputDir: string, bundlePath: string): void {
  const indexPath = path.join(outputDir, 'index.js')

  // path.relative returns 'a/b' or '../a/b'. Node's CommonJS resolver
  // requires the './' prefix on same-dir / nested paths.
  let relativeBundle = path.relative(outputDir, bundlePath)
  if (!relativeBundle.startsWith('.')) {
    relativeBundle = './' + relativeBundle
  }

  // On Windows, path.relative returns backslashes; require() needs forward.
  relativeBundle = relativeBundle.split(path.sep).join('/')

  const indexContent = `/**
 * WDK Bundle Exports
 * Generated by @tetherto/wdk-worklet-bundler
 */

const bundle = require('${relativeBundle}')

module.exports = {
  bundle
}
`
  fs.writeFileSync(indexPath, indexContent)
}

/**
 * Get default targets based on platform
 */
function getDefaultHosts (): string[] {
  return DEFAULT_BUNDLE_BUILD_HOSTS
}

/**
 * Generate WDK bundle from configuration
 */
export async function generateBundle (
  config: ResolvedConfig,
  options: GenerateBundleOptions = {}
): Promise<GenerateBundleResult> {
  const startTime = Date.now()
  const { dryRun, verbose, silent } = options

  const log = (msg: string): void => {
    if (!silent) console.log(msg)
  }

  const generatedDir = path.join(config.projectRoot, DEFAULT_OUTPUT_DIR)

  const isJsonRpc = config.transport === 'jsonrpc'
  const shouldLinkAddons = config.options?.linkAddons ?? isJsonRpc

  if (dryRun) {
    log(`Dry run - would generate (transport: ${config.transport ?? 'hrpc'}):`)
    log(`  Output dir: ${generatedDir}`)
    log(`  Entry: ${generatedDir}/wdk-worklet.generated.js`)
    log(`  Bundle: ${config.resolvedOutput.bundle}`)
    if (!options.skipTypes) {
      log(`  Types: ${config.resolvedOutput.types}`)
    }
    if (shouldLinkAddons) {
      for (const p of linkPlatformsForHosts(config.options?.targets ?? getDefaultHosts())) {
        log(`  Addons (${p}): ${config.resolvedOutput.addons[p]}`)
      }
    }

    return {
      success: true,
      bundlePath: config.resolvedOutput.bundle,
      typesPath: config.resolvedOutput.types,
      bundleSize: 0,
      duration: Date.now() - startTime
    }
  }

  try {
    // Ensure output directories exist
    fs.mkdirSync(generatedDir, { recursive: true })
    fs.mkdirSync(path.dirname(config.resolvedOutput.bundle), { recursive: true })

    // Step 1: Generate the worklet entry point or use the existing one
    let entryPath: string

    if (options.skipGeneration) {
      if (verbose) log('  Skipping artifact generation, using existing files...')

      entryPath = path.join(generatedDir, DEFAULT_ENTRY_FILENAME)

      if (!fs.existsSync(entryPath)) {
        throw new Error(`Artifacts not found at ${entryPath}. Run without --skip-generation first.`)
      }
    } else {
      if (verbose) log(`  Generating ${isJsonRpc ? 'JSON-RPC' : 'HRPC'} worklet entry point...`)
      entryPath = isJsonRpc
        ? await generateJsonRpcEntryPoint(config, generatedDir)
        : await generateEntryPoint(config, generatedDir)
      if (verbose) log(`    Entry: ${entryPath}`)
    }

    // Step 2: Pack the module graph
    const targets = config.options?.targets ?? getDefaultHosts()
    const convertEsmToCjs = shouldConvertEsmToCjs(config)

    // Missing peers marked optional via peerDependenciesMeta (e.g.
    // @ledgerhq/ledger-bitcoin for @bitcoinerlab/descriptors) are deferred so
    // bare-pack doesn't fail statically resolving imports the app never uses.
    // --no-defer-optional-peers disables this for apps that use those
    // features and want to find out at build time instead of runtime.
    let deferredPeers: string[] = []
    if (options.deferOptionalPeers !== false) {
      const { installed } = validateDependencies(getPackageList(config), config.projectRoot)
      deferredPeers = findMissingOptionalPeers(installed, config.projectRoot, { verbose })
      if (deferredPeers.length > 0) {
        log(`  Deferring missing optional peer dependencies: ${deferredPeers.join(', ')}`)
      }
    }

    if (verbose) {
      log(`  Packing for hosts: ${targets.join(', ')}`)
      if (convertEsmToCjs) log('  Converting ESM to CJS while packing...')
    }

    let packed
    try {
      packed = await packBundle({
        entry: entryPath,
        base: config.projectRoot,
        hosts: targets,
        linked: true,
        defer: deferredPeers,
        builtins: config.options?.builtins,
        convertEsmToCjs
      })
    } catch (packError) {
      if (packError instanceof MissingModuleError) {
        return {
          success: false,
          bundlePath: config.resolvedOutput.bundle,
          typesPath: config.resolvedOutput.types,
          bundleSize: 0,
          duration: Date.now() - startTime,
          error: `Missing module: ${packError.missingModule}`,
          missingModule: packError.missingModule
        }
      }

      const errorMsg = packError instanceof Error ? packError.message : String(packError)

      return {
        success: false,
        bundlePath: config.resolvedOutput.bundle,
        typesPath: config.resolvedOutput.types,
        bundleSize: 0,
        duration: Date.now() - startTime,
        error:
          `bare-pack failed: ${errorMsg}\n\n` +
          'This usually means:\n' +
          '  1. WDK modules are not installed in the project\n' +
          '  2. A dependency uses Node.js APIs not available in Bare runtime\n\n' +
          'Generated files are available at:\n' +
          `  Entry: ${entryPath}`
      }
    }

    const pack: GenerateBundlePackInfo = {
      id: packed.id,
      hosts: packed.hosts,
      files: packed.files,
      addons: packed.addons,
      containsEsm: packed.containsEsm,
      esmToCjs: packed.esmToCjs
    }

    if (packed.esmToCjs !== null) {
      log(`  ESM→CJS: converted ${packed.esmToCjs.converted} JS files, patched ${packed.esmToCjs.packagesPatched} package.json files`)
    } else if (isJsonRpc && packed.containsEsm) {
      // JSC and QuickJS cannot load ES modules: this bundle aborts at boot on
      // those engines. Not an error because V8 hosts load it fine.
      log('  ⚠️  Bundle contains ES modules and options.convertEsmToCjs is off; it will not load on JavaScriptCore (iOS/macOS) or QuickJS targets. Set options.convertEsmToCjs: true unless every target runs V8.')
    }

    // Step 3: Write the bundle in the wrapper its extension calls for
    const bundleSize = writeBundleFile(config.resolvedOutput.bundle, packed.bundle).length
    if (verbose) log(`    Bundle: ${config.resolvedOutput.bundle} (${packed.files} files, id ${packed.id})`)

    // Step 4: Link native addons (if enabled, or always for jsonrpc unless explicitly disabled)
    if (shouldLinkAddons) {
      if (verbose) log('  Linking native addons...')
      const addonsResult = await linkAddons(config, { verbose, silent, bundle: packed.bundle })
      if (!addonsResult.success) {
        // A missing or unlinkable addon crashes the worklet at its first
        // require on device, so the build fails here instead.
        return {
          success: false,
          bundlePath: config.resolvedOutput.bundle,
          typesPath: config.resolvedOutput.types,
          bundleSize,
          duration: Date.now() - startTime,
          pack,
          error: `Native addon linking failed: ${addonsResult.error ?? 'unknown error'}`
        }
      }
    }

    // Step 5: Generate TypeScript declarations (optional)
    if (!options.skipTypes) {
      if (verbose) log('  Generating TypeScript declarations...')
      generateTypeDeclarations(config)
    }

    // Step 6: Generate index.js for easy importing
    if (verbose) log('  Generating index.js...')
    generateIndexFile(generatedDir, config.resolvedOutput.bundle)

    return {
      success: true,
      bundlePath: config.resolvedOutput.bundle,
      typesPath: config.resolvedOutput.types,
      bundleSize,
      duration: Date.now() - startTime,
      pack
    }
  } catch (error) {
    return {
      success: false,
      bundlePath: config.resolvedOutput.bundle,
      typesPath: config.resolvedOutput.types,
      bundleSize: 0,
      duration: Date.now() - startTime,
      error: error instanceof Error ? error.message : String(error)
    }
  }
}

/**
 * Generate TypeScript declarations for the bundle
 */
function generateTypeDeclarations (config: ResolvedConfig): void {
  // Generate index.d.ts in .wdk folder for proper module resolution
  const generatedDir = path.join(config.projectRoot, '.wdk')
  const indexDtsPath = path.join(generatedDir, 'index.d.ts')
  fs.mkdirSync(generatedDir, { recursive: true })

  const networks = Object.keys(config.networks)
  const protocols = (config.protocols != null) ? Object.keys(config.protocols) : []

  const declarations = `
/**
 * WDK Bundle TypeScript Declarations
 * Generated by @tetherto/wdk-worklet-bundler
 * Generated at: ${new Date().toISOString()}
 */

export type NetworkName = ${networks.map((n) => `'${n}'`).join(' | ')};
export type ProtocolName = ${(protocols.length > 0) ? protocols.map((n) => `'${n}'`).join(' | ') : 'never'};

export const bundle: string;
`

  fs.writeFileSync(indexDtsPath, declarations)
}

/**
 * Generate only the entry point
 * Useful for debugging or custom bundling workflows
 */
export async function generateSourceFiles (
  config: ResolvedConfig,
  options: { verbose?: boolean } = {}
): Promise<{ entryPath: string }> {
  const generatedDir = path.join(config.projectRoot, DEFAULT_OUTPUT_DIR)

  // Generate worklet entry point (dispatch by transport)
  const isJsonRpc = config.transport === 'jsonrpc'
  if (options.verbose) console.log(`  Generating ${isJsonRpc ? 'JSON-RPC' : 'HRPC'} worklet entry point...`)
  const entryPath = isJsonRpc
    ? await generateJsonRpcEntryPoint(config, generatedDir)
    : await generateEntryPoint(config, generatedDir)

  // Generate index.js for easy importing (note: bundle won't exist yet in source-only mode)
  // Users will need to pack first, but we create the index anyway
  generateIndexFile(generatedDir, config.resolvedOutput.bundle)

  return {
    entryPath
  }
}
