/**
 * HRPC Generator
 * Generates HRPC bindings using hyperschema and hrpc libraries
 */

import fs from 'fs';
import path from 'path';
import { CORE_SCHEMA, HRPC_METHODS, SchemaEnum, SchemaStruct } from './schema-definitions';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const Hyperschema = require('hyperschema');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const HRPCBuilder = require('hrpc');

export interface HrpcGeneratorResult {
  schemaDir: string;
  hrpcDir: string;
  schemaJsonPath: string;
  hrpcJsonPath: string;
}

function isSchemaEnum(def: SchemaEnum | SchemaStruct): def is SchemaEnum {
  return 'enum' in def;
}

/**
 * Generate hyperschema from definitions
 */
function generateHyperschema(outputDir: string): string {
  const schemaDir = path.join(outputDir, 'schema');
  fs.mkdirSync(schemaDir, { recursive: true });

  // Create new hyperschema instance
  const schema = new Hyperschema();

  // Get or create namespace
  const ns = schema.namespace('wdk-core');

  // Process each schema definition
  for (const def of CORE_SCHEMA) {
    if (isSchemaEnum(def)) {
      // Handle enum
      ns.register({
        name: def.name,
        enum: def.enum.map((e) => e.key),
        offset: def.offset !== undefined ? def.offset : 1,
      });
    } else {
      // Handle struct
      ns.register({
        name: def.name,
        compact: def.compact !== undefined ? def.compact : false,
        flagsPosition: def.flagsPosition !== undefined ? def.flagsPosition : 0,
        fields: def.fields.map((field) => ({
          name: field.name,
          type: field.type,
          required: field.required !== undefined ? field.required : false,
        })),
      });
    }
  }

  // Generate schema files - toDisk expects directory path as second argument
  Hyperschema.toDisk(schema, schemaDir);

  return schemaDir;
}

/**
 * Generate hrpc.json file
 */
function generateHrpcJson(outputDir: string): string {
  const hrpcJsonDir = path.join(outputDir, 'hrpc-src');
  fs.mkdirSync(hrpcJsonDir, { recursive: true });

  const hrpcJson = {
    version: 1,
    schema: HRPC_METHODS,
  };

  const hrpcJsonPath = path.join(hrpcJsonDir, 'hrpc.json');
  fs.writeFileSync(hrpcJsonPath, JSON.stringify(hrpcJson, null, 2));

  return hrpcJsonDir;
}

/**
 * Generate schema.json file (for reference/debugging)
 */
function generateSchemaJson(outputDir: string): string {
  const schemaJsonPath = path.join(outputDir, 'schema.json');

  const schemaJson = {
    version: 1,
    schema: CORE_SCHEMA,
  };

  fs.writeFileSync(schemaJsonPath, JSON.stringify(schemaJson, null, 2));

  return schemaJsonPath;
}

/**
 * Generate HRPC bindings from schema
 */
function generateHrpcBindings(schemaDir: string, hrpcJsonDir: string, outputDir: string): string {
  const hrpcOutputDir = path.join(outputDir, 'hrpc');
  fs.mkdirSync(hrpcOutputDir, { recursive: true });

  // Generate HRPC bindings using hrpc library
  const builder = HRPCBuilder.from(schemaDir, hrpcJsonDir);
  HRPCBuilder.toDisk(builder, hrpcOutputDir);

  // Also copy messages.js (same as schema/index.js)
  const schemaIndexPath = path.join(schemaDir, 'index.js');
  const messagesPath = path.join(hrpcOutputDir, 'messages.js');

  if (fs.existsSync(schemaIndexPath)) {
    const content = fs.readFileSync(schemaIndexPath, 'utf-8');
    const updatedContent = content.replace(
      /\/\/ This file is autogenerated by the hyperschema compiler/,
      '// This file is autogenerated by the hyperschema compiler\n// Used by generated/hrpc/index.js'
    );
    fs.writeFileSync(messagesPath, updatedContent);
  }

  return hrpcOutputDir;
}

/**
 * Generate all HRPC files
 */
export async function generateHrpc(outputDir: string): Promise<HrpcGeneratorResult> {
  // Ensure output directory exists
  fs.mkdirSync(outputDir, { recursive: true });

  // Generate schema.json for reference
  const schemaJsonPath = generateSchemaJson(outputDir);

  // Generate hrpc.json
  const hrpcJsonDir = generateHrpcJson(outputDir);
  const hrpcJsonPath = path.join(hrpcJsonDir, 'hrpc.json');

  // Generate hyperschema
  const schemaDir = generateHyperschema(outputDir);

  // Generate HRPC bindings
  const hrpcDir = generateHrpcBindings(schemaDir, hrpcJsonDir, outputDir);

  return {
    schemaDir,
    hrpcDir,
    schemaJsonPath,
    hrpcJsonPath,
  };
}

/**
 * Copy existing HRPC files from a source directory (for migration)
 */
export function copyExistingHrpc(sourceDir: string, outputDir: string): HrpcGeneratorResult {
  const hrpcDir = path.join(outputDir, 'hrpc');
  const schemaDir = path.join(outputDir, 'schema');

  fs.mkdirSync(hrpcDir, { recursive: true });
  fs.mkdirSync(schemaDir, { recursive: true });

  const sourceHrpcDir = path.join(sourceDir, 'generated/hrpc');
  const sourceSchemaDir = path.join(sourceDir, 'generated/schema');

  // Copy HRPC files
  if (fs.existsSync(sourceHrpcDir)) {
    for (const file of fs.readdirSync(sourceHrpcDir)) {
      fs.copyFileSync(path.join(sourceHrpcDir, file), path.join(hrpcDir, file));
    }
  }

  // Copy schema files
  if (fs.existsSync(sourceSchemaDir)) {
    for (const file of fs.readdirSync(sourceSchemaDir)) {
      fs.copyFileSync(path.join(sourceSchemaDir, file), path.join(schemaDir, file));
    }
  }

  return {
    schemaDir,
    hrpcDir,
    schemaJsonPath: path.join(sourceDir, 'schema.json'),
    hrpcJsonPath: path.join(sourceDir, 'src/hrpc/hrpc.json'),
  };
}
