import fs from 'fs'
import path from 'path'
import os from 'os'
import { generateWalletModulesCode } from '../../src/generators/wallet-modules'
import { generateEntryPoint } from '../../src/generators/entry'
import type { ResolvedConfig } from '../../src/config/types'

describe('Code Generators', () => {
  const createMockConfig = (overrides?: Partial<ResolvedConfig>): ResolvedConfig => ({
    networks: {
      ethereum: {
        package: '@tetherto/wdk-wallet-evm-erc-4337'
      },
      polygon: {
        package: '@tetherto/wdk-wallet-evm-erc-4337'
      }
    },
    protocols: {},
    configPath: '/test/wdk.config.js',
    projectRoot: '/test',
    resolvedOutput: {
      bundle: '/test/.wdk/wdk.bundle.js',
      types: '/test/.wdk/wdk.d.ts',
      addons: {
        ios: '/test/ios/addons',
        macos: '/test/macos/addons',
        android: '/test/android/addons'
      },
      addonsYml: '/test/addons.yml'
    },
    ...overrides
  })

  describe('generateWalletModulesCode', () => {
    it('should generate core module import', () => {
      const config = createMockConfig()
      const code = generateWalletModulesCode(config)

      expect(code).toContain("const _wdkModule = require('@tetherto/wdk', { with: { imports: 'bare-node-runtime/imports' } })")
      expect(code).toContain('WDK = _wdkModule.default || _wdkModule.WDK || _wdkModule')
    })

    it('should generate wallet module imports', () => {
      const config = createMockConfig()
      const code = generateWalletModulesCode(config)

      expect(code).toContain("if (network === 'ethereum') _mod = require('@tetherto/wdk-wallet-evm-erc-4337', { with: { imports: 'bare-node-runtime/imports' } })")
      expect(code).toContain('if (_mod) _walletCache[network] = _mod.default || _mod')
    })

    it('should map networks to wallet managers', () => {
      const config = createMockConfig()
      const code = generateWalletModulesCode(config)

      expect(code).toContain("if (network === 'ethereum') _mod = require('@tetherto/wdk-wallet-evm-erc-4337'")
      expect(code).toContain("if (network === 'polygon') _mod = require('@tetherto/wdk-wallet-evm-erc-4337'")
      expect(code).toContain("has: (_, network) => ['ethereum', 'polygon'].includes(network)")
    })

    it('should handle preload modules', () => {
      const config = createMockConfig({
        preloadModules: ['spark-frost-bare-addon']
      })
      const code = generateWalletModulesCode(config)

      expect(code).toContain("require('spark-frost-bare-addon')")
      expect(code).toContain('// Preload modules')
    })

    it('should handle multiple wallet modules', () => {
      const config = createMockConfig({
        networks: {
          ethereum: {
            package: '@tetherto/wdk-wallet-evm-erc-4337'
          },
          spark: {
            package: '@tetherto/wdk-wallet-spark'
          }
        }
      })
      const code = generateWalletModulesCode(config)

      expect(code).toContain("if (network === 'ethereum') _mod = require('@tetherto/wdk-wallet-evm-erc-4337'")
      expect(code).toContain("if (network === 'spark') _mod = require('@tetherto/wdk-wallet-spark'")
      expect(code).toContain("has: (_, network) => ['ethereum', 'spark'].includes(network)")
    })
  })

  describe('generateEntryPoint', () => {
    let tempDir: string

    beforeEach(() => {
      tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'wdk-entry-test-'))
    })

    afterEach(() => {
      fs.rmSync(tempDir, { recursive: true, force: true })
    })

    it('should create entry file in output directory', async () => {
      const config = createMockConfig()
      const entryPath = await generateEntryPoint(config, tempDir)

      expect(fs.existsSync(entryPath)).toBe(true)
      expect(entryPath).toBe(path.join(tempDir, 'wdk-worklet.generated.js'))
    })

    it('should include generated header comment', async () => {
      const config = createMockConfig()
      const entryPath = await generateEntryPoint(config, tempDir)
      const content = fs.readFileSync(entryPath, 'utf-8')

      expect(content).toContain('Auto-generated by @tetherto/wdk-worklet-bundler')
      expect(content).toContain('DO NOT EDIT MANUALLY')
    })

    it('should include core dependencies', async () => {
      const config = createMockConfig()
      const entryPath = await generateEntryPoint(config, tempDir)
      const content = fs.readFileSync(entryPath, 'utf-8')

      expect(content).toContain("require('bare-node-runtime/global')")
      expect(content).toContain("require('@tetherto/pear-wrk-wdk/worklet'")
    })

    it('should include RPC handlers', async () => {
      const config = createMockConfig()
      const entryPath = await generateEntryPoint(config, tempDir)
      const content = fs.readFileSync(entryPath, 'utf-8')

      expect(content).toContain('registerRpcHandlers(rpc, context)')
      expect(content).toContain('const rpc = new HRPC(BareIPC)')
    })

    it('should include wallet modules code', async () => {
      const config = createMockConfig()
      const entryPath = await generateEntryPoint(config, tempDir)
      const content = fs.readFileSync(entryPath, 'utf-8')

      expect(content).toContain("require('@tetherto/wdk'")
      expect(content).toContain("require('@tetherto/wdk-wallet-evm-erc-4337'")
    })

    it('should create output directory if it does not exist', async () => {
      const config = createMockConfig()
      const nestedDir = path.join(tempDir, 'nested', 'output')

      const entryPath = await generateEntryPoint(config, nestedDir)

      expect(fs.existsSync(nestedDir)).toBe(true)
      expect(fs.existsSync(entryPath)).toBe(true)
    })
  })
})
